# Generated by Django 5.0 on 2023-12-09 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_rename_pets_pet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pet',
            new_name='Pets',
        ),
    ]
