#cloud_journey/docker-compose.yml
version: '3'
services:
  app:
    build: src
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"